### ISSUE TITLE
NO IMAGES

### ISSUE THREAD

**Issue by alexissosa88** [Sky-CSC/OSR#34]
Good afternoon, you are not showing me the images of the champion selection, is there any step that can be done about it? thank you so much
![image](https://github.com/Sky-CSC/OSL/assets/82295311/e83d35be-373b-4a32-964b-12f68981f2e7)

**Comment by Sky-CSC** [comment]
Resolved in #36 [link](https://github.com/Sky-CSC/OSL/issues/36#issuecomment-2211414094)
