### ISSUE TITLE
Aurora add at fr_fr

### ISSUE THREAD

**Issue by EugenXkonovalov** [Sky-CSC/OSR#37]
can some one tell/show how to update to 14.15 ore put Aurora in shampionselect ? I cant use the last update but with the fr_fr from other Issue fix with fr_fr,but Aurora dont show up in selction.

**Comment by Sky-CSC** [comment]
For version 1.2.0 and earlier, the patch assets do not download correctly. Copy the folder (patch number) to `OSL-Web-1.2.0-win-x64/wwwroot/assets/`.
Patch 14.15 : 
[Zip link](https://drive.google.com/file/d/12XW2arC68Oqa_3o3u72Rsy5bWLUrAvAe/view?usp=sharing)
[Folder link](https://drive.google.com/drive/folders/1g-FN7HYipVsvpg2CRrG89pEK3iaOwoW3?usp=drive_link)
