### ISSUE TITLE
OSL client dont work

### ISSUE THREAD

**Issue by Marcowodzu** [Sky-CSC/OSR#38]
I need to ask, about this overlay. 

Overlay works after vanguard enters to LOL?

I tried to install OSL overlay, but OSL client didn't want to start.

I tried to start, when i was observer

![Zrzut ekranu 2024-08-26 162320](https://github.com/user-attachments/assets/1ec0d2d1-0c95-4044-8aaf-be7d1bd9602d)

**Comment by Sky-CSC** [comment]
Hi
Here's the link to the fix : [Fix OSL-Client](https://github.com/Sky-CSC/OSL/issues/36#issuecomment-2173956026)

**Comment by Marcowodzu** [comment]
Thank you, that resolved my problem, but now i have problem with liveEvents data. Do you have idea how can i resolve this one?

![Zrzut ekranu 2024-08-27 190823](https://github.com/user-attachments/assets/6a084f8d-00e5-49e4-a101-a0fbd19d5e2f)

**Comment by Sky-CSC** [comment]
This is normal, live event API are removed by riot [link](https://github.com/SkinSpotlights/LiveEventsDocumentation)
I work on new version of application but it takes time ;)

**Comment by Marcowodzu** [comment]
Thank you for your answer. I will be waiting ;>
